name = "chickadee"
main = "./src/index.ts"
compatibility_date = "2024-04-01"

[assets]
directory = "dist"

[vars]
ENVIRONMENT = "production"
BASIC_USERNAME = "admin"

[[analytics_engine_datasets]]
binding = "ENGINE"
dataset = "chickadee"

[observability]
enabled = true
head_sampling_rate = 1.0

[placement]
mode = "smart"
