name = "chickadee"
main = "./dist/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"

[vars]
ENVIRONMENT = "prod"
ENGINE_DATASET = "chickadee"
BASIC_USERNAME = "admin"

[[analytics_engine_datasets]]
binding = "ENGINE"
dataset = "chickadee"

[[kv_namespaces]]
binding = "KV"
id = "59b4b7859e5c472ea94a4a3e47d050e4"

[observability]
enabled = true
head_sampling_rate = 1.0

[placement]
mode = "smart"
